- name: CHANGE TOWER BASE URL
  tower_settings:
    name: TOWER_URL_BASE
    value: "https://{{username}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    tower_verify_ssl: no
    tower_host: localhost
    tower_username: admin
    tower_password: "{{admin_password}}"

#https://docs.ansible.com/ansible-tower/latest/html/administration/init_script.html
- name: TURN OFF TOWER
  shell: ansible-tower-service stop

- name: INSTALL SSL KEY
  template:
    src: ssl_key.j2
    dest: /etc/tower/tower.key

- name: COMBINE SPECIFIC AND INTERMEDIATE CERT
  template:
    src: combined_cert.j2
    dest: /etc/tower/tower.cert

- name: TURN ON TOWER
  shell: ansible-tower-service start
