- name: Perform Checks to make sure this Playbook will complete successfully
  hosts: localhost
  connection: local
  become: no
  gather_facts: yes
  tasks:
    - name: make sure we are running correct Ansible Version
      assert:
        that:
          - ansible_version.major >= 2
          - ansible_version.minor >= 8

    - name: make sure workshop_type is set to a correct value
      assert:
        that:
          - workshop_type is defined
          - workshop_type in valid_workshop_types
        msg: "workshop_type must be defined and be one of: {{valid_workshop_types}}"

    - name: make sure network_type is set to a correct value
      assert:
        that:
          - network_type is defined
          - network_type in valid_network_types
        msg: "network_type must be defined and be one of: {{valid_network_types}}"
      when: workshop_type == "networking"

    - name: run role to check if local environment setup will work with AWS
      include_role:
        name: aws_check_setup

    - name: make sure we are not running with TESTWORKSHOP as the name so no overlap
      assert:
        that:
          - ec2_name_prefix != "TESTWORKSHOP"

    - name: make sure packages required are installed on this control node
      pip:
        name:
          - netaddr
      check_mode: yes
      when: workshop_type == "networking"
      register: package_state

    - name: fail if previous check has changed
      assert:
        that:
          - package_state.changed != True

    - name: auto license feature for Ansible Tower
      block:
        - name: Check that the provided license exists
          stat:
            path: "{{playbook_dir}}/tower_license.json"
          register: stat_result
        - debug:
            var: stat_result
        - fail:
            msg: "autolicense is turned on, but we need a license located at {{playbook_dir}}/tower_license.json"
          when:
           - not stat_result.stat.exists
      when:
       - autolicense is defined
       - autolicense

    - name: Install required roles onto THIS machine
      shell: "ansible-galaxy install {{item}} -f --force-with-deps -p ./roles/"
      loop:
        - 'geerlingguy.repo-epel'
        - 'ansible_security.ids_config'
        - 'ansible_security.ids_install'
      when:
        - workshop_type == "security"

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - manage_ec2_instances

- name: wait for all nodes to have SSH reachability
  hosts: "managed_nodes:control_nodes"
  become: yes
  gather_facts: no
  roles:
    - connectivity_test

- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  gather_facts: no
  become: yes
  roles:
    - user_accounts
    - common
  tags: control_node

- name: CONFIGURE CONTROL NODE
  hosts: control_nodes
  gather_facts: no
  become: yes
  roles:
    - control_node
  tags: control_node

- name: ADD DNS ENTRIES FOR ALL STUDENT TOWER NODES
  hosts: control_nodes
  become: yes
  gather_facts: no
  roles:
    - { role: aws_dns, when: create_login_page is defined and create_login_page and not dme_account_key is defined}
    - { role: dnsmadeeasy, when: create_login_page is defined and create_login_page and dme_account_key is defined}
  tags: control_node

- name: Setup Amazon S3 Website for Student Login
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  roles:
    - { role: aws_workshop_login_page, when: create_login_page is defined and create_login_page }
  tags: control_node

- name: include workshop_type unique setup roles
  import_playbook: "{{workshop_type}}.yml"

- name: Alert the mothership
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
    - { include_role: {name: tower_request}, when: student_total > 9 }

- name: print out information for instructor
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
    - name: set facts for output
      set_fact:
        summary_information: |
          PROVISIONER SUMMARY
          *******************
          - Workshop name is {{ec2_name_prefix}}
          - Instructor inventory is located at  {{playbook_dir}}/{{ec2_name_prefix}}/instructor_inventory.txt
          - Private key is located at {{playbook_dir}}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem
          {{website_information}}
          FAILURES
          *******************
          {{dns_information}}

    - name: Print Summary Information
      debug:
        msg: "{{summary_information}}"
